Repository NervanaSystems/ngraph-tf, pull requests merged in 2018-11, with the labels that each got.

#289 Sindhu/tf unittest inputfromfile
  test/python/tests_to_run.txt
  test/python/tf_unittest_runner.py
Labels: Fully Reviewed

#285 Shrestha/Cluster Nodes According to Matching Deadness Predicate
  src/ngraph_assign_clusters.cc
  src/ngraph_mark_for_clustering.cc
  src/tf_deadness_analysis.cc
  src/tf_deadness_analysis.h
  test/graph_rewrites/assign_clusters.cc
  test/graph_rewrites/deadness_test.cc
Labels: Fully Reviewed

#296 Shrestha/minor readme changes
  README.md
  diagnostics/README.md
  diagnostics/model_test/README.md
Labels: Fully Reviewed

#300 Mingshan/Eliminates one additional transpose
  src/ngraph_builder.cc
Labels: Fully Reviewed

#304 Shrestha/changes ngraph config.disable
  src/ngraph_api.cc
  src/ngraph_mark_for_clustering.cc
  src/ngraph_rewrite_pass.cc
Labels: Fully Reviewed

#302 - Show calculated norm value for both passed and failed case
  diagnostics/model_test/verify_model.py
Labels: Fully Reviewed

#298 kanvi/ssd_vgg16_bug
  src/ngraph_encapsulate_op.cc
Labels: Fully Reviewed

#307 Fix transformer-LT bug
  src/ngraph_builder.cc
  test/python/test_softmax.py
Labels: Fully Reviewed

#291 sarkars/Initial commit for quantized custom op
  CMakeLists.txt
  src/ngraph_builder.cc
  src/ngraph_mark_for_clustering.cc
  src/ngraph_utils.cc
  src/ngraph_utils.h
  test/test_nn_ops.cpp
Labels: Fully Reviewed

#317 Langjian/klocwork bugs
  src/ngraph_builder.cc
  src/ngraph_tracked_variable.cc
  src/tf_graphcycles.cc
Labels: Fully Reviewed

#319 sarkars/Print exception message
  test/python/tensorflow/tf_unittest_runner.py
Labels: Fully Reviewed

#321 Update PlaidML ngraph->ngraph_config
  python/CreatePipWhl.cmake
Labels: Fully Reviewed, PlaidML

#316 Added the option to use pre-built TF CC library for unit tests
  CMakeLists.txt
  build_ngtf.py
  test/CMakeLists.txt
  test/ci/run-premerge-ci-checks.sh
Labels: Release Candidate

#292 Added a feature so that I can extend the RPATH settings
  CMakeLists.txt
Labels: Release Candidate

#308 Sarkars/strided slice 1
  src/ngraph_builder.cc
  src/ngraph_mark_for_clustering.cc
  test/python/test_slice.py
  test/test_array_ops.cpp
Labels: Release Candidate

#310 Use output of forward pooling in ngraph::op::MaxPoolBackprop
  src/ngraph_builder.cc
Labels: Future Change, Release Candidate

#328 Modify Mac builds to use TensorFlow 1.12.0 for builds
  test/ci/macos/run-ngraph-tf-mac-build.sh
Labels: Release Candidate

#327 Sindhu/tf_unittest invalid test names, empty lines in list of tests file.
  test/python/tensorflow/tests_to_run.txt
  test/python/tensorflow/tf_unittest_runner.py
Labels: Fully Reviewed, Release Candidate

#314 Shrestha/op executor tensor creation
  src/ngraph_backend_manager.h
  src/ngraph_encapsulate_op.cc
  src/ngraph_freshness_tracker.h
  test/opexecuter.cpp
  test/opexecuter.h
Labels: Fully Reviewed, Release Candidate

#334 Added support for adding license files to the whl
  CMakeLists.txt
  python/CreatePipWhl.cmake
  python/setup.in.py
  src/CMakeLists.txt
Labels: Release Candidate

#329 Replaced the 'ngraph_config' with 'ngrph_bridge' and the wheel name
  README.md
  build_ngtf.py
  diagnostics/README.md
  diagnostics/model_test/verify_model.py
  diagnostics/ngtf_graph_viewer.py
  examples/README.md
  examples/axpy.py
  examples/keras_sample.py
  examples/mnist/mnist_cnn_inference.py
  examples/mnist/mnist_deep_simplified.py
  examples/mnist/mnist_deep_simplified_distributed.py
  examples/mnist/mnist_fprop_only.py
  python/CreatePipWhl.cmake
  python/ngraph_bridge/__init__.in.py
  python/setup.in.py
  src/ngraph_rewrite_pass.cc
  test/ci/run-premerge-ci-checks.sh
  test/install_test.py
  test/python/common.py
  test/python/tensorflow/tf_unittest_ngraph.patch
  test/resnet_unit_test.py
Labels: Release Candidate

#340 Mingshan/Adding floor_mod test with negative int and float inputs
  test/test_math_ops.cpp
Labels: Fully Reviewed, Release Candidate

#339 Shrestha/ngraph config update
  python/ngraph_bridge/__init__.in.py
  src/ngraph_api.cc
  src/ngraph_api.h
  src/ngraph_backend_manager.cc
  src/ngraph_backend_manager.h
  src/ngraph_mark_for_clustering.cc
  test/opexecuter.cpp
  test/python/test_set_backend.py
Labels: Fully Reviewed, Release Candidate

#341 Added the AVX512 support. Also fixed the pip whl file name to contain…
  CMakeLists.txt
  README.md
  build_ngtf.py
  python/setup.in.py
  src/version.cc
Labels: Release Candidate

#342 Fixed klockworks errors
  src/ngraph_builder.cc
Labels: Fully Reviewed, Release Candidate
