Repository NervanaSystems/ngraph-tf, pull requests merged in 2018-10, with the labels that each got.

#227 Sindhu/implement argmaxop
  src/ngraph_builder.cc
  src/ngraph_mark_for_clustering.cc
  test/test_math_ops.cpp
Labels: Fully Reviewed

#190 using weakptr for backend
  CMakeLists.txt
  src/ngraph_encapsulate_op.cc
Labels: bug

#243 Kanvi/implement any op
  src/ngraph_builder.cc
  src/ngraph_mark_for_clustering.cc
  test/test_math_ops.cpp
Labels: Fully Reviewed

#247 Mingshan/Size op
  src/ngraph_builder.cc
  src/ngraph_mark_for_clustering.cc
  test/test_array_ops.cpp
Labels: Fully Reviewed

#245 Kanvi/implement zeroslike
  src/ngraph_builder.cc
  src/ngraph_mark_for_clustering.cc
  test/test_array_ops.cpp
Labels: Fully Reviewed

#183 Langjian/allreduce
  CMakeLists.txt
  examples/mnist/mnist_deep_simplified_distributed.py
  src/ngraph_builder.cc
  src/ngraph_mark_for_clustering.cc
Labels: Fully Reviewed

#250 updated for new ngraph API change
  CMakeLists.txt
  src/ngraph_encapsulate_op.cc
  src/ngraph_utils.cc
  src/ngraph_utils.h
  test/graph_exec.cpp
  test/opexecuter.cpp
Labels: Fully Reviewed

#249 Shrestha/Unit Test FW : Add APIs to allow execution only on nGraph or on TF
  test/conversions.cpp
  test/graph_exec.cpp
  test/graph_rewrites/assign_clusters.cc
  test/opexecuter.cpp
  test/opexecuter.h
  test/padding.cpp
  test/test_array_ops.cpp
  test/test_math_ops.cpp
  test/test_nn_ops.cpp
  test/test_utilities.cpp
  test/test_utilities.h
  test/tf_exec.cpp
Labels: Fully Reviewed

#252 Added the necessary cmake files for abseil library
  CMakeLists.txt
  src/CMakeLists.txt
  third-party/CMakeLists.txt
Labels: Fully Reviewed

#253 Shrestha/unit test fw support multiple backends
  test/opexecuter.cpp
  test/opexecuter.h
  test/test_nn_ops.cpp
Labels: Fully Reviewed

#259 Shrestha/fix for tf master changes
  src/ngraph_mark_for_clustering.cc
  src/ngraph_version_utils.h
  src/tf_deadness_analysis.cc
  src/tf_deadness_analysis.h
Labels: Fully Reviewed

#262 Shrestha/Fix Bug in Rewrite For Tracking. Manifested in RESNET when enabled with XLA
  src/ngraph_rewrite_for_tracking.cc
  src/tf_deadness_analysis.cc
Labels: Fully Reviewed

#261 Sindhu/Python tf_test_runner to test tensorflow python tests
  test/python/tf_unittest_runner.py
Labels: Fully Reviewed

#268 Add libsdl1.2-dev to Dockerfile for Python3, to run A3C model
  test/ci/docker/Dockerfile.ngraph-tf-ci-py3
Labels: Release Candidate

#266 Avijit/rel 0.7.0 preperation
  CMakeLists.txt
  README.md
  python/ngraph/__init__.in.py
  python/setup.in.py
  test/build_tf_cc.sh
Labels: Fully Reviewed, Release Candidate

#276 Fix of tensor liveness issue
  src/ngraph_encapsulate_op.cc
Labels: Fully Reviewed, Release Candidate

#257 Added Cmake changes related to Centos build.
  CMakeLists.txt
  src/CMakeLists.txt
Labels: Release Candidate

#270 kanvi/move_ngraph_disable_flag
  src/ngraph_capture_variables.cc
  src/ngraph_mark_for_clustering.cc
  src/ngraph_rewrite_pass.cc
Labels: Fully Reviewed, Release Candidate

#274 sarkars/Support multiple outputs, or all outputs
  diagnostics/model_test/mnist_cnn.json
  diagnostics/model_test/verify_model.py
Labels: Fully Reviewed, Release Candidate

#260 Mingshan/Support SpaceToDepth and DepthToSpace in the bridge
  src/ngraph_builder.cc
  src/ngraph_mark_for_clustering.cc
  test/test_array_ops.cpp
  test/test_utilities.cpp
  test/test_utilities.h
Labels: Release Candidate

#269 sarkars/Support scaled unsigned mode correctly
  src/ngraph_builder.cc
  test/test_array_ops.cpp
Labels: Fully Reviewed, Release Candidate

#271 Sarkars/reenable python tests
  test/ci/run-premerge-ci-checks.sh
  test/python/common.py
  test/python/conftest.py
  test/python/test_api.py
  test/python/test_avgpoolbackprop.py
  test/python/test_conv2dbackpropinput.py
  test/python/test_depthwiseconv2d.py
  test/python/test_elementwise_ops.py
  test/python/test_floor.py
  test/python/test_fusedbatchnorm.py
  test/python/test_l2loss.py
  test/python/test_maxpoolbackprop.py
  test/python/test_prod.py
  test/python/test_relu6.py
  test/python/test_relugrad.py
  test/python/test_sigmoid.py
  test/python/test_sign.py
  test/python/test_softmax.py
  test/python/test_sparse_softmax_cross_entropy_with_logits.py
  test/python/test_stack.py
Labels: Fully Reviewed

#282 Sindhu/tf unittest regexsupport
  test/python/tf_unittest_runner.py
Labels: Fully Reviewed

#281 sarkars/Adding prints to ASSERT_EQs and comparing tensor shapes correctly
  test/graph_exec.cpp
  test/graph_rewrites/assign_clusters.cc
  test/opexecuter.cpp
  test/test_utilities.cpp
  test/test_utilities.h
Labels: Fully Reviewed

#287 R0.7 changes merge to master
  README.md
  diagnostics/model_test/verify_model.py
  python/CreatePipWhl.cmake
  python/ngraph/__init__.in.py
  python/setup.in.py
  src/CMakeLists.txt
  src/ngraph_api.cc
  src/ngraph_api.h
  src/version.cc
  src/version.h
  test/build_tf_cc.sh
  test/python/common.py
Labels: Fully Reviewed

#286 Shrestha/Add clustering information to NGRAPH_TF_LOG_PLACEMENT.
  src/ngraph_deassign_clusters.cc
Labels: Fully Reviewed

#277 sarkars/Quantized_max_pool
  src/ngraph_builder.cc
  src/ngraph_mark_for_clustering.cc
  test/test_array_ops.cpp
  test/test_nn_ops.cpp
Labels: Fully Reviewed

#256 Mingshan/conv2dbackpropinput c++ test
  test/test_nn_ops.cpp
Labels: Fully Reviewed

#279 Update to the new ngraph batch norm API
  CMakeLists.txt
  src/ngraph_builder.cc
Labels: Fully Reviewed
