Repository NervanaSystems/ngraph-tf, pull requests merged in 2018-12, with the labels that each got.

#346 Fixed the march flags et. al
  CMakeLists.txt
  build_ngtf.py
  python/CreatePipWhl.cmake
  src/CMakeLists.txt
Labels: Release Candidate

#349 Doc update
  README.md
  examples/README.md
  python/CreatePipWhl.cmake
  python/setup.in.py
Labels: Release Candidate

#355 Sarkars/softmax multidim
  src/ngraph_builder.cc
  test/test_nn_ops.cpp
Labels: Fully Reviewed

#345 Support multiple random value range for multiple input tensors
  diagnostics/model_test/README.md
  diagnostics/model_test/mnist_cnn.json
  diagnostics/model_test/template.json
  diagnostics/model_test/verify_model.py
Labels: Fully Reviewed

#358 Sindhu/Fix SplitV segfault
  src/ngraph_builder.cc
Labels: Fully Reviewed

#347 Sindhu/Fix TF Python Slicetest segfault
  src/ngraph_builder.cc
  test/python/test_slice.py
Labels: Fully Reviewed

#333 Mingshan/Added floor_div unit tests for negative integer and float inputs
  test/test_math_ops.cpp
Labels: Fully Reviewed

#361 Shrestha/fix tf python kernel tests conv ops test.conv2 d test.test op edge cases
  src/ngraph_builder.cc
  test/python/test_conv2D_KernelChecks.py
Labels: Fully Reviewed

#357 Langjian/batch norm unittest
  src/ngraph_builder.cc
Labels: Fully Reviewed

#367 Shrestha/ Dequantize Op is supported only in 'Scaled' mode.
  src/ngraph_mark_for_clustering.cc
  test/test_array_ops.cpp
Labels: Fully Reviewed

#368 Shrestha/fix tf master compilation error and upgrade nGraph version
  CMakeLists.txt
  build_ngtf.py
  src/ngraph_encapsulate_op.cc
  test/graph_exec.cpp
  test/opexecuter.cpp
  test/opexecuter.h
Labels: Fully Reviewed

#365 Sindhu/List of Tensorflow python tests to run with Ngraph
  test/python/tensorflow/python_tests_list.txt
  test/python/tensorflow/tests_to_run.txt
Labels: Release Candidate

#359 Fboemer/external project fix
  CMakeLists.txt
  cmake/external_gtest.cmake
  python/CreatePipWhl.cmake
  test/CMakeLists.txt
  test/ci/docker/docker-scripts/run-ngraph-tf-build.sh
  third-party/CMakeLists.txt
Labels: Release Candidate

#371 Sindhu/Fix python slice_op_test failure
  src/ngraph_builder.cc
  test/python/tensorflow/python_tests_list.txt
  test/python/test_slice.py
Labels: Fully Reviewed, Release Candidate

#352 Support backend configuration strings
  src/ngraph_backend_manager.cc
Labels: Release Candidate

#363 Avijit/fix mac build
  CMakeLists.txt
  build_ngtf.py
  test_ngtf.py
Labels: Fully Reviewed, Release Candidate

#372 Release 0.9.0 prep.
  CMakeLists.txt
  README.md
  build_ngtf.py
  python/setup.in.py
  src/version.cc
Labels: Release Candidate

#375 Sindhu/Implement Rank Op
  src/ngraph_builder.cc
  src/ngraph_mark_for_clustering.cc
  test/test_array_ops.cpp
Labels: Fully Reviewed

#377 fixed the compilation error for mac build
  src/ngraph_builder.cc
Labels: Fully Reviewed
