Repository NervanaSystems/ngraph-tf, pull requests merged in 2019-02, with the labels that each got.

#409 sarkars/Rejecting NCHW_VECT_C data format for spacetodepth and depthtospace
  src/ngraph_builder.cc
  src/ngraph_mark_for_clustering.cc
Labels: Fully Reviewed

#423 sindhu/minor fix for Rank Op, which will not get placed on ngraph without this
  src/ngraph_mark_for_clustering.cc
Labels: Fully Reviewed

#433 Fix memory leak
  CMakeLists.txt
  build_ngtf.py
  src/ngraph_encapsulate_op.cc
Labels: Release Candidate

#434 Add bazel support to build nGraph
  .gitignore
  README.md
  bazel/BUILD
  bazel/README.md
  bazel/WORKSPACE
  bazel/ngraph.BUILD
  bazel/nlohmann_json.BUILD
  bazel/tf_configure/BUILD
  bazel/tf_configure/BUILD.tpl
  bazel/tf_configure/tf_configure.bzl
  configure_bazel.sh
  examples/tf_cpp_examples/Makefile
  examples/tf_cpp_examples/README.md
  examples/tf_cpp_examples/hello_tf.cpp
  test_ngtf.py
Labels: Fully Reviewed, Release Candidate

#439 Avijit/r0.11 final
  CMakeLists.txt
  README.md
  bazel/BUILD
  bazel/WORKSPACE
  bazel/ngraph.BUILD
  build_ngtf.py
  python/ngraph_bridge/__init__.in.py
  python/setup.in.py
  src/version.cc
  test_ngtf.py
Labels: Release Candidate

#440 Allow non-const min/maxes for quantize and dequantize ops
  src/ngraph_builder.cc
  src/ngraph_mark_for_clustering.cc
Labels: Fully Reviewed
