Repository NervanaSystems/ngraph-tf, pull requests merged in 2019-01, with the labels that each got.

#388 Preparation for Release 0.10
  CMakeLists.txt
  README.md
  build_ngtf.py
  python/setup.in.py
  src/version.cc
Labels: Fully Reviewed

#381 Sindhu/Implement Conv3D Op
  src/ngraph_builder.cc
  src/ngraph_builder.h
  src/ngraph_conversions.h
  src/ngraph_mark_for_clustering.cc
  test/test_nn_ops.cpp
Labels: Fully Reviewed

#389 Mingshan/maxpool3d
  src/ngraph_builder.cc
  src/ngraph_mark_for_clustering.cc
  test/python/tensorflow/python_tests_list.txt
  test/test_nn_ops.cpp
Labels: Fully Reviewed

#378 Mingshan/rewind DepthToSpace translation to have three reshapes instead of two
  src/ngraph_builder.cc
Labels: Fully Reviewed

#397 Sarkars/edge contraction logging
  src/ngraph_assign_clusters.cc
  src/ngraph_encapsulate_clusters.cc
Labels: Fully Reviewed

#400 Sarkars/log placement corrections
  src/ngraph_assign_clusters.cc
  src/ngraph_deassign_clusters.cc
  src/ngraph_encapsulate_clusters.cc
  src/ngraph_mark_for_clustering.cc
  src/ngraph_utils.cc
  src/ngraph_utils.h
Labels: Fully Reviewed

#366 Langjian/distributed json
  CMakeLists.txt
  build_ngtf.py
  examples/mnist/mnist_softmax_distributed.py
  src/ngraph_encapsulate_op.cc
  src/ngraph_mark_for_clustering.cc
  src/ngraph_rewrite_pass.cc
Labels: Fully Reviewed

#404 Mingshan/Adding Squeeze Fix for negative squeeze dimensions
  src/ngraph_builder.cc
  test/test_math_ops.cpp
Labels: Fully Reviewed

#399 Copy ngraph plaidml auto-detect logic
  CMakeLists.txt
Labels: PlaidML

#407 Update Readme with the build instructions when building on Broadwell
  README.md
Labels: Release Candidate

#408 Avijit/r0.10.0-rc1
  CMakeLists.txt
  README.md
  build_ngtf.py
  python/setup.in.py
  src/version.cc
Labels: Release Candidate

#330 Get libplaidml from the plaidml package
  python/CreatePipWhl.cmake
  python/ngraph_bridge/__init__.in.py
Labels: PlaidML

#414 Sarkars/verify models with given inputs
  diagnostics/model_test/mnist_cnn_with_inputs.json
  diagnostics/model_test/mnist_inputs/inp_import_Placeholder-0.npy
  diagnostics/model_test/verify_model.py
Labels: Fully Reviewed

#410 Sarkars/quant conv ops
  src/ngraph_builder.cc
  src/ngraph_mark_for_clustering.cc
  src/ngraph_utils.cc
Labels: Fully Reviewed

#415 Add some more detailed noncontraction logging
  src/ngraph_assign_clusters.cc
Labels: Fully Reviewed
