Repository NervanaSystems/ngraph-tf, pull requests merged in 2019-04, with the labels that each got.

#473 Sindhu/onehot op
  src/ngraph_builder.cc
  src/ngraph_mark_for_clustering.cc
  test/test_array_ops.cpp
Labels: Fully Reviewed

#477 Add support for CentOS 7.6 builds in docker containers
  test/ci/docker/docker-scripts/run-as-user.sh
  test/ci/docker/docker-scripts/run-build-test-ngtf.sh
  test/ci/docker/dockerfiles/Dockerfile.ngraph_tf.build_ngtf_centos76_py34
Labels: Fully Reviewed

#480 Sindhu/Rel 0.12.0-rc2 prep
  CMakeLists.txt
  README.md
  build_ngtf.py
  python/setup.in.py
  src/version.cc
Labels: Fully Reviewed

#482 Sindhu/ngraph-v0.17.rc.1
  CMakeLists.txt
  bazel/WORKSPACE
  build_ngtf.py
  src/ngraph_builder.cc
  test/python/tensorflow/python_tests_list.txt
  test/test_array_ops.cpp
Labels: Fully Reviewed, Release Candidate

#484 Avijit/more test refactoring
  test/ci/buildkite/test_runner.py
  tools/test_utils.py
Labels: Fully Reviewed

#490 Avijit/add "include" directory to whl and few enhancements
  build_ngtf.py
  maint/apply-code-format.sh
  maint/check-code-format.sh
  python/CreatePipWhl.cmake
  python/ngraph_bridge/__init__.in.py
  python/setup.in.py
  src/CMakeLists.txt
  src/version.cc
  src/version.h
  test/ci/buildkite/test_runner.py
  test_ngtf.py
  tools/build_utils.py
  tools/test_utils.py
Labels: Fully Reviewed

#469 Sarkars/bypass ngtf
  src/ngraph_builder.cc
  src/ngraph_mark_for_clustering.cc
  src/ngraph_mark_for_clustering.h
  test/python/tensorflow/python_tests_list.txt
  test/python/test_gather.py
  test/test_array_ops.cpp
Labels: Fully Reviewed

#489 Sarkars/nmsv4
  src/ngraph_builder.cc
  src/ngraph_mark_for_clustering.cc
Labels: Fully Reviewed

#500 Shrestha/fix tensor destructor seg fault
  src/enable_variable_ops/ngraph_assign_op.cc
  src/enable_variable_ops/ngraph_encapsulate_op.cc
  src/enable_variable_ops/ngraph_enter_in_catalog.cc
  src/enable_variable_ops/ngraph_tracked_variable.cc
  src/enable_variable_ops/ngraph_var.h
  src/ngraph_backend_manager.cc
  src/ngraph_encapsulate_op.cc
Labels: Fully Reviewed

#488 Sindhu/Update Select Op to accept more complex shapes as inputs
  src/ngraph_builder.cc
  test/python/test_select.py
Labels: Fully Reviewed

#507 Fixed Klockworks error, bunch or warnings and removed dead code
  src/ngraph_builder.cc
  src/ngraph_encapsulate_op.cc
  src/ngraph_tracked_variable.cc
  test/test_array_ops.cpp
Labels: Release Candidate

#502 Changes GatherV2 indices to Node
  src/ngraph_builder.cc
  src/ngraph_mark_for_clustering.cc
Labels: Release Candidate

#498 Kanvi/patch files for models
  test/grappler/README.md
  test/grappler/a3c_ng_optimizer.patch
  test/grappler/benchmark_cnn_ng_optimizer.patch
  test/grappler/build_ng_optimizer.patch
  test/grappler/dcgan_inference_bench_ng_optimizer.patch
  test/grappler/draw_inf_ng_optimizer.patch
  test/grappler/eval_image_classifier_ng_optimizer.patch
  test/grappler/fastgen_ng_optimizer.patch
  test/grappler/infer_detections_ng_optimizer.patch
  test/grappler/inference_model_ng_optimizer.patch
  test/grappler/misc_utils_ng_optimizer.patch
  test/grappler/ncf_main_ng_optimizer.patch
  test/grappler/train_squeezenet_ng_optimizer.patch
  test/grappler/trainer_lib_ng_optimizer.patch
  test/grappler/unet_ng_optimizer.patch
  test/grappler/wide_deep_ng_optimizer.patch
Labels: Release Candidate

#485 kanvi/Grappler optimizer improvements
  src/grappler/ngraph_optimizer.cc
  src/grappler/ngraph_optimizer.h
  src/ngraph_capture_variables.cc
  src/ngraph_capture_variables.h
  src/ngraph_mark_for_clustering.cc
  src/ngraph_mark_for_clustering.h
  src/ngraph_rewrite_pass.cc
  test/graph_rewrites/backend_manager_test.cc
  test/graph_rewrites/deadness_test.cc
Labels: Fully Reviewed, Release Candidate

#506 fix build problem for when building from `build_nnp.py --distributed`
  src/ngraph_utils.cc
  tools/build_utils.py
Labels: Release Candidate

#521 Minor Fix for building with --Variable version
  src/enable_variable_ops/ngraph_capture_variables.cc
  src/enable_variable_ops/ngraph_rewrite_pass.cc
Labels: Fully Reviewed

#511 Sindhu/model accuracy ckpt location change
  diagnostics/model_accuracy/verify_inference_model.py
Labels: Fully Reviewed, Release Candidate

#524 Sindhu/Encap refactor to use ifdef with variable op
  src/CMakeLists.txt
  src/enable_variable_ops/ngraph_encapsulate_op.cc
  src/ngraph_encapsulate_op.cc
Labels: Fully Reviewed

#522 Changes in MNIST script
  examples/mnist/mnist_cnn_inference.py
  examples/mnist/mnist_deep_simplified.py
  examples/mnist/mnist_deep_simplified_distributed.py
Labels: Fully Reviewed

#527 shrestha/Bug Fix if-def
  src/ngraph_encapsulate_op.cc
Labels: Fully Reviewed, Release Candidate

#530 Kanvi/tf python tests
  test/python/tensorflow/README.md
  test/python/tensorflow/tf_unittest_ngraph_with_grappler.patch
Labels: Fully Reviewed, Release Candidate

#528 update regex, tolerance to verify accuracy
  diagnostics/model_accuracy/verify_inference_model.py
Labels: Release Candidate
